### ISSUE TITLE
.nest folder is not randomly generated at $HOME on GitHub Actions

### ISSUE THREAD

**Issue by dazy1030** [mtj0928/nest#23]
（タイトルだけ英語で書きましたが日本語で失礼します。）

表題の通りですが、GitHub Actionsでnestのインストールを行うと `~/.nest` にインストールが行われないことがあります。ほとんどの場合は失敗し稀に成功します。

https://github.com/dazy1030/playground/actions/workflows/blank.yml

（👆のアクションでは ~#10までなぜか `ls -la` をしてますが、 `ls -la $HOME` すべきでした）

**Comment by mtj0928** [comment]
ご報告ありがとうございます。
現在のnestはmacOSしかサポートしておらず、linux環境はサポートしていません(READMEに書くべきでした)
一度macOS環境で試していただけますか？

**Comment by mtj0928** [comment]
あ、勘違いしていました、macOSで実行されていますね。
確認してみます。

**Comment by mtj0928** [comment]
@dazy1030 
この現象を理解しました。

----

インストールするスクリプトの中で以下を実行しています。
```sh
./extracted_files/nest.artifactbundle/nest-$VERSION-macos/bin/nest install mtj0928/nest > /dev/null
```
これはややこしいのですが、`nest`を使って`nest`をインストールしています。

このコマンドの内部で、未認証の状態でGitHubのAPIを叩いているのですが、同一のIPからのrate limitに引っかかってしまっており、artifact bundleのインストールに失敗しています。(おそらくマシンを共有している他のactionsの中でもAPIを叩いていると予想されます)
これが成功したりしなかったりする理由です。

また`nest`はartifact bundleのインストールに失敗した際にはリポジトリをクローンしてビルドするのですが、ご用意されたGitHub Actionsの環境だと、swiftのバージョンが古く、nestをビルドできません。(nestのビルドにはSwift 6以上が必要です。)

この問題の解決策は二つあります。
#### 1. 環境変数を用いてトークンを設定する
nestは`GH_TOKEN`という環境変数を見て、もしトークンがあれば、そのトークンを用いてGitHubのAPIを叩きます。
なのでGitHub actionsで渡される環境変数 `GITHUB_TOKEN` をそのまま`GH_TOKEN`に渡せば良さそうです。
```yaml
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

#### 2. Swift 6.0をインストールする
Xcodeのバージョンを切り替えたり、個別にswiftをインストールするなどして、Swiftのバージョンを6.0以降にすることで、artifact bundleのインストールに失敗しても、ビルドしてインストールすることができます。

2つの方法を紹介しましたが、1の方法の方がビルド時間がかからないのでお勧めです。
ぜひ一度試してみてください。

**Comment by dazy1030** [comment]
爆速確認ありがとうございます…！
なるほどです… マシンガチャに当たると成功したって感じ…ですかね？

数回程度ですが、1の方法で失敗しなくなったことを確認しました。Swiftの環境は問題なく用意できましたが、もともと成果物のビルドをしないことを目的にnestを使わせていただいていたので、1の方法を取りたいと思います。

問題は解決できましたのでcloseします。ありがとうございました！！
